### ISSUE TITLE
Prototype Update - Divisional Tracking

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#1694]
Title of ticket: Prototype Update - Divisional Tracking

#### Description
Updating Design of Divisional Tracking based off of needs of Ministry Users that came out in Training

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Add Due Date Optional Window for Ministries to Select if they wish
- [x] Add E-APP# window to be able to track at any stage
- [x] Update Comments based off of this

**Comment by JHarrietha-AOT** [comment]
Updated Design: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/768088423

Updated Comment: "_Education Programs_ division has been updated to stage _Gathering Records_ E-App/Other reference Number _0000000_ Due on _YYYY MM DD_"

**Comment by JHarrietha-AOT** [comment]
Dev ticket has been estimated with designs. Moving to closed
