### ISSUE TITLE
Help secton

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1954]
## Description:	
- Short Description of the needed Epic in the below format

* As a ministry coordinator and IAO analyst
* I want a help section with videos and documentation
* so that I can learn understand how to take actions in the new FOI system

* What are the most critical features being built as part of this Epic

Information architecture of help materials

* Expected Outcome – Justification why this Feature must be built, what is expected value and justification for priority.

Users will be able to troubleshoot and unblock themselves.
----
**Sizing**

* T-shirt size: 

 [ x] S
 [ ] M
 [ ] L
 [ ] XL

(S=1-2 Sprints, M=2-3 Sprints, L=4-5 Sprints, XL=not sure, probably more than 5 Sprints). 

* *Risks and Assumptions**

1. [ ] What are assumptions?
Users want a help section.
2. [ ] What are the risks?
3. [ ] Have we done an RFC on a technical approach?
4. [x ] Are the dependencies (technical, business, regulatory/policy) known?
A resource to create the videos
5. [ ] Has work on this Epic been prioritized with key stakeholders?
Yes
