### ISSUE TITLE
Who should be included as a sign off authority in divisional tracking? 

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#2000]
Title of ticket: 

#### Description
During April training with EDUC, we were asked if we could include GCPE as one of the sign off divisions listed. Some ministries track GCPE, but eApps does not include them. There is  discussion to have around this about ease of use for users vs organizational protocols 

#### DOD
- [ ] Loren/Matt to discuss with ED
- [ ] Circle back with team
- [ ] Circle back with ministries
- [ ] 
- [ ]

**Comment by mpilchar** [comment]
cc: @m-prodan @KaraBeach @lmullane
