### ISSUE TITLE
Regression Testing - 392, 398 , 400 (US #1674 , #1834, #1884)

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2117]
Title of ticket: 

#### Description
Regression Test functionalities assigned from Nick on sheet, covering US #1674 , #1834, #1884

#### Dependencies
Are there any dependencies?

#### DOD
- [x]  Functional Test on all browsers(Edge, Chrome, FireFox) - US #1674 and Test ID - 392
- [x] Functional Test on all browsers(Edge, Chrome, FireFox) - US #1884 and Test ID - 400
- [x]  Functional Test on all browsers(Edge, Chrome, FireFox) - US #1834 and Test ID - 398
- [x]  demo bugs to team and Logs Bugs in Zenhub with reproduction bugs
- [x]  CONFIRM tests on STAGING
