### ISSUE TITLE
Divisional Tracking Updates - EDU and LBR

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#2139]
Title of ticket: Divisional Tracking Updates 

#### Description
Update Divisional Tracking to be consistent with current state of each Ministry, only EDU and LBR have changes

LBR divisional tracking should be: 
Minister’s Office
Deputy Minister’s Office
Assistant Deputy Minister’s Office 
Management Services

EDU divisional tracking should be:
Deputy Minister’s Office
Minister’s Office 
Education Programs
Governance & Analytics
Learning
Resource Management
Services & Technology
Child Care
Minister of State

#### DOD - EDUCATION
- [x] ADD - Child Care
- [x] ADD - Minister of State

#### DOD - LABOUR
- [x] REMOVE - Employment Advisor's Office
- [x] REMOVE - Employment Standards
- [x] REMOVE - Policy and Legislation
- [x] REMOVE - Workers' Advisors Office
- [x] REMOVE - Labour
- [x] ADD - Assistant Deputy Minister's Office

**Comment by mpilchar** [comment]
This will be a minor release following Release 2.1 push to pilot

**Comment by m-prodan** [comment]
Nice work team - all good, tested various stages and updates with due dates. All comments populating as expected and no errors. Also checked across other ECON sector Ministries and no issues there either.
