### ISSUE TITLE
ETL for FOI FLOW Requests with status and related meta data to Data warehouse 

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2452]
Title of ticket: 

#### Description
During the refinement meeting for #2297 , it being found that Average days on Request Statuses, Ministry Assigned To information is required to complete "Pref. Dashboard" merge task developing by @nkan-aot .  So decided to import Request status specific information along with Ministry assignment data from FOI FLOW database. So that, it will be beneficial for Pilot ministries. 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Create DIM and FACT migration scripts for FOI FLOW Request statuses and related metadata. review fields with @nkan-aot 
- [x]  Develop SSIS ETL  packages for DIM, FACT
- [x]  Deploy and schedule to DEV, TEST
- [ ] 
- [ ]
