### ISSUE TITLE
Fee Processing - Findings

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#2955]
Title of ticket: 

#issues as of 7/NOV/2022, in this excel.
[https://app.zenhub.com/files/358004325/f68b87bd-1df0-4979-8f85-5872e34fb327/download](https://app.zenhub.com/files/358004325/f68b87bd-1df0-4979-8f85-5872e34fb327/download)

#### Issue Description and Solutions
- [x] Change in Amount Paid throws console error

- [x] Inflight request CFR form status is non editable for ministry in Fee Estimate and On Hold state

**Solution/Explanation**
Make it editable for ministry in Fee Estimate and On Hold state for the 1st version.

- [x] Add request is allowing to save the request without selecting the Program Area

**Solution/Explanation**
Update the validation for the save button

- [x] Receipt template spacing updates

- [x] Issue on Mobile View - Coordinate and work with @JHarrietha-AOT  , Business for Mobile View , footer links - refer comment
- [x] Replace FormsFlow favicon on browsertab for payment forms with BC GOV  - refer comment

**Solution/Explanation**

Update the Title and logo of the browser same as FOI application

- [x] Missing BC GOV LOGO on Receipt  - refer comment

**Solution/Explanation**
Move logo to the body. Keep the transaction id in the header.

- [x] AMOUNT PAID disabling  - refer comment (effort moved to #3004)
- [x] Fixed Bug#1 : On the payment form of PayBC amount is different from the Approved CFR Form Value. 

**Solution/Explanation**
Update the code to get the fee information if the CFR form is approved. 

- [x] Fixed Bug#2 : -ve amount is going to the applicant for the payment - Refer attached excel

**Solution/Explanation**

Stop sending email to applicant if the balanceremaning < 0

- [x] Confirm functionality : Email message for 0.00 CFR Form balance , after actuals from Ministry, IAO

**Solution/Explanation**

0 or -ve balance remaining then on Hold option is not there for Response dropdown. So no email send to the applicant

- [x] Confirm functionality : Email message for  -VE Balance / refund

**Solution/Explanation**
No email send for 0 or -ve balance remaining.

- [x] Confirm functionality : -ve balance remaining vs Refund amount on the CFR Form

**Solution/Explanation**
_ve balance remaining will stay as is. Refund is a free text and no calculation applied.

- [x] Confirmation needed: Response to Records Review Modal is requesting for an attachment. Is it required?

**Solution/Explanation**
No change needed now as attachment is not a mandatory for the state change.

- [x] Formio.Forms throws error when you open payonline for the first time.

**Solution/Explanation**
No fix needed for this issue. This is a known issue with formsflow. It will not affect the functionality.
**reference**: https://githubhelp.com/aot-technologies/forms-flow-ai/issues/106

- [x] Fix for Camunda error: org.camunda.bpm.engine.context           : ENGINE-16004 Exception while closing command context: ENGINE-02004 No outgoing sequence flow for the element with id 'Gateway_1ui9vly' could be selected for continuing the process. This error occurs only in local.

**Solution/Explanation**
This is happening only with local docker. Adding isIMAPEnabled variable in the dockercompose will fix this issue.

- [x] contact applicant log shows incorrect email and attachments when sent email manually.

**Solution/Explanation**
The email was getting replaced with latest. Added condition to replace only specific emails and not the receipt email

- [x] sometimes OnHold option is disabled and not clickable

**Solution/Explanation**
Cannot reproduce in local. We will keep monitoring the issue.

- [x] create new version of cfr form CFR state and then change the state to fee estimate and approve. Send email using correspondence log. Pay the amount and change the state to CFR manually. Try to update the actuals. It is non editable as the status is still "in review with IAO".

**Solution/Explanation**
Don't change the CFR status for Fee Estimate state for the different versions of CFR Form. It should happen only for the 1st time. In any state, the CFR Form status should stay as is. except Fee estimate for the 1st time.

- [x] replace applicant and assignee details in the contact applicant email template

**Solution/Explanation**
Applicant name and Assignee name are already getting replaced in the preview page. Bring the changes to template itself.

- [x] open the attached file in new window

**Solution/Explanation**
Add target of a tag to "_blank"

- [x] CFR to Fee Estimate. In Fee estimate state, the "Contact Applicant" scenario failed. Is this valid use case ?

**Solution/Explanation**
Add correspondence should be disabled for Fee Estimate state as per the discussion with business.

- [x] balance remaining shows -ve value

**Solution/Explanation**
There can be -ve balance remaining, if
1. The amount paid > 0
2. there is a fee waiver carry forward from the previous form

- [x] balance remaining shows NaN, actual and estimated total shows undefined

**Solution/Explanation**
Add validations to the calculation of balance remaining. This issue is happening only for old requests where the fee waiver property is missing in the DB.

- [x] Remove "none" option from email template dropdown

**Solution/Explanation**
Remove the option from the FE code.

#### Dependencies
Are there any dependencies?

**Comment by abin-aot** [comment]
@JHarrietha-AOT  - How about we work on this mobile responsive view for payment forms , since its public facing?  
@lmullane  , @m-prodan : This wont that much time, and its worth investing at least 4-5 hours to make it look good. Thoughts?
Here are the points, we need to consider 

-  Footer is taking too much of real estate, blocking the button below

- Text size need to be reduced as per resolution

- We need to have working links on the footer , because its public facing form

- Top right hamburger menu can be removed



![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/cbd90fac-b0f5-458b-8c79-c5c65196bbfa)

**Comment by abin-aot** [comment]
Replace Payment forms/web app's favicon on  Browser with BC GOV favicon
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/6bada9ab-79f8-445b-a950-6a0c194105bb)

**Comment by abin-aot** [comment]
Missing logo receipt!
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/1fedbfe3-69fe-4fd1-ba57-dcbe9f9eadd6)

**Comment by lmullane** [comment]
> @JHarrietha-AOT - How about we work on this mobile responsive view for payment forms , since its public facing? @lmullane , @m-prodan : This wont that much time, and its worth investing at least 4-5 hours to make it look good. Thoughts? Here are the points, we need to consider
> 
> * Footer is taking too much of real estate, blocking the button below
> * Text size need to be reduced as per resolution
> * We need to have working links on the footer , because its public facing form
> * Top right hamburger menu can be removed
> 
> ![image.png](https://camo.githubusercontent.com/a6ae1e51ab2dcc20040e3f2c6a093c7c84013a4ce233987f2e8b20761c432f87/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630376465356161666564666162303838333934323763342f63626439306661632d623066352d343538622d386337392d633563363531393662626661)

Agreed it is worth the investment, @abin-aot

**Comment by abin-aot** [comment]
AMOUNT PAID ENABLED issue, after actuals
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/e29a7025-f7dd-429b-bf92-ec512cebc757)

**Comment by abin-aot** [comment]
Refer this https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/bcgov/foi-flow/3135 . Closing since effort is over!
