### ISSUE TITLE
Fee Payment Points to validate on test , Flow understanding and known issues before Prod Fee payment  release

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3135]
**Describe the bug in current situation**
Fee Payment Points to validate on test , Flow understanding and known issues before Prod release of Fee Payment.  The purpose of this task is to confirm the fixes done on the issues found during dev-integration testing and issues logged ,parked for later moment,

#### Bugs found , Process flows which need to be tested

- [x]  Test Inflight requests with CFR  Fee payment Flow - This is  to replicate the scenarios on existing FOI Requests on PROD. Requested business to create FOI requests at different states(Intake, CFR, Fee Estimate, harms, Review, closed etc.) prior to TEST release for Fee Payment.

- [x]  Emailing to Applicant flow : -ve and zero amount payment has no emails to applicant. Decision made with Business

- [x] CFR forms  - Amount Paid will be disabled based on the discussions on #3004

- [x] Make sure the Amount payment for applicant is exactly the same as latest "Approved" CFR Forms, AND whatever CFR form value which is "in progress" has no impact on the email send using "correspondence log"

- [ ] Mobile view / Hand held views for the applicant payments should be appropriate 

- [x] Information(Logo, Phone, Address, language) indicated on the Receipts, Payment forms, Footer links need to be accurate.

 - [ ] -ve Balance and Refund amount has no relation as of now. This will be seperate and Refund amount has no influence on the Calculation. 

- [ ] Validations for Contact Applicant Log Template Options

Fee Estimate Option will be enabled only if below conditions are true

1. Latest CFR Form should be in approved state
2. Balance remaining should be > 0
3. TotalActualDue <=0
4. States allowed: CFR, OnHold (User can use Fee Estimate option from contact applicant log only in these states)

**Contact applicant option is not available for Fee Estimate state.**

Outstanding Fee Option will be enabled only if below conditions are true

1. Latest CFR Form should be in approved state
2. Balance remaining should be > 0
3. TotalActualDue > 0
4. States allowed: OnHold (User can use Outstanding Fee option from contact applicant log only in these states)

- [ ]  Known issue1 : OnHold to Response automatic state change for a "Outstanding" email sent from "Correspondence Log" , will be handled at later point or with future user stories for automatic state change. at present escape route is to ask ministry to change the state for IAO to move to Response or will ask dev team to create temp mechanism.

- [ ] Known issue2 : Accidently changing a CFR Form with "zero balance" or only electronic page estimate, which the CFR form in Limbo, unless IAO decides to enter a mock value into Actuals and give it back or other BE escape route , Will solve in future #3128

- [ ] Known  behavior  : Scroll mouse issue - Digits will unknowingly increase/decrease on CFR form by mistake!

- [ ] Known  Issue : CFR history - V1 having wrong values - #EDU-2022-15111213 - Will solve in  future #3129

- [ ] Known Issue :  CFR Estimate email communication wont work with requests opened form  Redirect state - Issue already logged! #3063

- [ ] Known Issue : Known Issue :  Attachment uploads on Extensions to FOI Requests throws error  , this happens only if we tries to create an extension other than syncing from AXIS. will solve later - #3125

- [ ] Known Behavior : Any estimated CFR fee calculation on CFR Form for version greater than  1, should be the sum up value from previous as per current business processes with IAO and ministry  **and/or if there are any mistakes in those digits and steps can CAUSE mismatch in Fee calculation**. Also, assuming that the errors happening to Balance remaning, with various permutations combinations on CFR forms, has been confirmed by business. Demonstrated to entire team( @lmullane, @m-prodan)   and its confirmed that there is no need for engineering solution for that process as of now! 

- [ ] Known Issue: Contact Applicant add correspondence button is sometimes clickable even when no templates are selectable - front end only will fix after prod release

 - [ ] Fixed Issue: Confirmation Modal when user approves CFR form - ensure message is new text and does not reference moving back to in review from approved

 - [ ] Known Issue: User is able to save new version of CFR form after only selecting reason - need additional validation to ensure user enters some info in the estimates - front end only will fix after prod release

 - [ ] Known Issue: User is able to send email through contact applicant even after request is closed - will fix after prod release

 - [ ] Known Issue: Any existing active payment links need to be disabled if request is closed - will fix after prod release #3137

**Comment by m-prodan** [comment]
Checked off the first box - Test Inflight requests with CFR Fee payment Flow - This is to replicate the scenarios on existing FOI Requests on PROD. Requested business to create FOI requests at different states(Intake, CFR, Fee Estimate, harms, Review, closed etc.) prior to TEST release for Fee Payment.

I have tested the in-flight requests staged, and ran into minimal issues. I have specific instructions to give to users for requests that are already in the on-hold or fee estimate state, as there are some steps users will need to take if they want to minimize issues.

**Comment by lmullane** [comment]
@abin-aot, tomorrow at standup, let's confirm what we need to QA here.

**Comment by abin-aot** [comment]
@lmullane : Nothing more need to be QA'd  since its in prod now. this ticket was created like an MOU on known issues, edge conditions etc before our PROD release. Now most of the flows are known to all, hence known issue can be taken as per the priority and particular flows which cause confusion can handled as per our planning.
