### ISSUE TITLE
Divisional Tracking Update - TRA

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3272]
Title of ticket: 

#### Description
This is related to ticket #3191

Although closed and deployed to production - it was not technically done as required. Ministry requested a specific order, and not the default alphabetical order.

In addition - some new divisions that were previously missed by the client have been added.

#### DOD
Add and update the division so the **order is exactly as presented**

- [x] Deputy Minister’s Office
- [x] Minister's Office
- [x] Minister of State
- [x] Corporate Writing Services
- [x] Finance & Risk Management Division
- [x] Highways & Regional Services Division
- [x] Headquarters
- [x] Northern Region
- [x] South Coast Region
- [x] Southern Interior Region
- [x] Commercial Vehicle Safety & Enforcement
- [x] Passenger Transportation Branch
- [x] Integrated Transportation & Infrastructure Services Division
- [x] Policy, Programs, & Partnerships Division
- [x] Strategic & Corporate Priorities Division
- [x] BC Railway Company
- [x] BC Transit
- [x] BC Transportation Finance Authority
- [x] Transportation Investment Company

**Comment by m-prodan** [comment]
Ticket added per our conversation @abin-aot 

cc: @lmullane

**Comment by liseandtea** [comment]
Re-tested on TRA-2023-30123

Divisions are now in the order requested by TRA and the missing 3 groups have been added.

![Screenshot 2023-01-13 103719.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/841a58e8-104c-499b-82f8-5d72acf01084)

![Screenshot 2023-01-13 103805.jpg](https://images.zenhubusercontent.com/633f19609b1468159fc7d8b5/b1fe101d-c3d2-4b71-8ff4-f96c1a17ce94)

**Comment by abin-aot** [comment]
Reduced estimate to 3 from 5, Created Release label 4.8.1 for this ticket - FYI @lmullane , @m-prodan , @liseandtea

**Comment by abin-aot** [comment]
Deployment to PROD is over! 
**Steps taken**

1. Backs up taken  - Camunda, PostgresDB
patroni-master-002-ffa-camunda_2023-01-16_16-10-15.sql.gz  
patroni-master-002-foidb_2023-01-16_16-10-13.sql.gz
2, ![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/d057ea9f-bb18-47a2-9d43-19603dfa4e8c)
