### ISSUE TITLE
Package & Release

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3335]
## Description:	
- Short Description of the needed Epic in the below format

* As an FOI analyst
* I want to package records
* so that they can be sent as a redline for ministry sign off and to the applicant once approved

* What are the most critical features being built as part of this Epic

FOI analyst creates the redline
Ministry coordinator exports the redline
Ministry coordinator uploads the redline with annotations back into the system
FOI analyst creates the records package
FOI analyst sends the records package to the applicant through the corporate SFTP service

* Expected Outcome – Justification why this Feature must be built, what is expected value and justification for priority.
Applicant receives their records package
----
**Sizing**

* T-shirt size: 

 - [x] S
 [ ] M
 [ ] L
 [ ] XL

(S=1-2 Sprints, M=2-3 Sprints, L=4-5 Sprints, XL=not sure, probably more than 5 Sprints). 

* *Risks and Assumptions**

1. [ ] What are assumptions?
2. [ ] What are the risks?
3. [ ] Have we done an RFC on a technical approach?
4. [x] Are the dependencies (technical, business, regulatory/policy) known?
5. [ ] Has work on this Epic been prioritized with key stakeholders?

**Comment by lmullane** [comment]
Dependency with SFTP service.
