### ISSUE TITLE
Project On-boarding ,  Familiarisation on  FOI  Modernisation Project  and Preparation for Katalon Automation script updates

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3390]
Title of ticket: 

#### Description
The purpose of this task is to  gather, acquire , try out all functional and non- functional features , process flows of FOI FLOW - Request Management, FOI Request Submission, FOI Reporting apps. Also, understand  the data flow from AXIS, AXIS Sync 

**Note** :  For time being @nimya-aot  can work using dev/test Keycloak accounts until IDIR , VPN access is ready

#### Dependencies
Are there any dependencies?
- [x] IDIR Access
- [x] Access to VPN - but can temporarily use Dev-marshal for app familiarisation 
- [x] Access to Open-shift Projects ( DEV, TEST)

#### DOD
- [x]  Gather all update to date information like Miro Board links for (WorkFlows etc) , Acceptance Test Scripts(Excel spread sheets) and Code Repo branches information.
- [x]  Set up FOI FLOW on local Docker. #1) Check out DEV / DEV-NK-AutomationScripts branch from git repo and deploy to local
- [x]  Try out FOI FLOW - Request Management - Add Request ,  Queue (My request / Teams /. Watching ), Advanced Search
- [x] FOI Request Submission App - DEV . Requests Submitted can be viewed under "UNopened" state.
- [x]  Understand various #1) types of Request - Personal vs General. #2) States - Intake In Progress to Response. 
- [x]  Various Roles and Authorisations involved  for IAO [ Intake , Flex and  Different Types of Processing Teams - Central, Social Tech , etc.] - Refer updated Miro board !
- [x] Review Keycloack Group set ups - IAO , Ministry Team groups. 
- [x] Ministry Team'/ User access - #1 ) Queue - Differences of Ministry Queue vs IAO Queue. #2) Information exposed for a Ministry User vs IAO User
- [x]  Due Calculation Logic - #1) LDD , CFR due Date. #2) Extensions - OIPC , Public Body, #3) Onhold
- [x]  CFR Forms Logic - #1) Estimated Fee vs Actual  #2) Fee Payment
- [x]  Attachments , Comments - functionalities  - Tags, User Tagging
- [x] AXIS Sync Logic  , Information pulled from AXIS, its validation etc. 
- [x]  Restricted Requests - IAO vs MInistry Restricted Requests - New!
- [x] Get Access to AXIS TEST (ITEST)  - @abin-aot  to do!. Try out creating requests there and Sync to FOI FLOW App
- [x]  Reporting Dashboards!  - Familiarise Combined Dashboards - SSO from FOI FLOW

**Comment by abin-aot** [comment]
@nimya-aot  , Access to http://itest.axis.gov.bc.ca/ATIPXpress/ given , please try using your IDIR. Please create new requests on this AXIS environment to try our Sync and other logic
