### ISSUE TITLE
UX Design - Assorted Small Design Updates

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#3447]
Title of ticket: UX Design - Assorted Small Design Updates

#### Description
This ticket is to cover assorted small design updates that need to be made 
#### Dependencies
Are there any dependencies?

#### DOD
- [x] Designs for Ticket #3231
- [x] Designs for Ticket #3437
- [x] Designs for Ticket #3301
- [x] Designs for Ticket #3302
- [x] Designs for Ticket #3421

**Comment by lmullane** [comment]
@JHarrietha-AOT, 

@abin-aot, flagged that we need a design for #3241 to notify the user when that the export will take some time (i.e. the processing time to stitch the PDF together).

@m-prodan, will be updating the AC for #3241 once you have a design and @divyav-aot will pick up the story when she returns next Monday.

**Comment by JHarrietha-AOT** [comment]
@lmullane @m-prodan 

I have combined the designs for #3231 & #3437. I am hoping to avoid adding multiple buttons thats don't have a CTA that is used throughout the redaction process. It is something that is used to generate the files at specific times. I noticed this in the 4 tickets that have been these quick turn around designs - they were all to add additional buttons. When adding a button for each action isn't always the best solution, so to help ensure that we leave room for growth on the screen and also don't confuse users with way to main primary and secondary buttons like AXIS has. 

Let me know if you have any questions or comments:

ACTIVE: https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/981498459

INACTIVE: https://jacklyn808742.invisionapp.com/console/share/8QVPHCNXSGA/981498460 
Because user has note assigned flags to every page

**Comment by JHarrietha-AOT** [comment]
@lmullane @m-prodan 

Again, took a similar approach as #3231/#3437/#3302. to avoid a series of buttons I have combined into a dropdown so users can download separate versions of the records as need in the process. 

Design for #3301 & #3241
In process (if back end is compiling any of the download options)
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423262

Active and ready to download: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/977423264

Download Harms - download in divisional folders with no redline
Download Redline for Sign Off - download in divisional folders with redline boxes and sections
Download Final Package - Final Package for ministry users to be able to access and see final redactions applied
