### ISSUE TITLE
Event Queue

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3819]
## Description:	
- Short Description of the needed Epic in the below format
- A way to track events (state changes and user comments) for all requests at the assigned, watcher and team level.

* As an IAO analyst and ministry coordinator
* I want a way to easily find what is happening with all the requests assigned to me or my team
* so that I know what actions I need to take

* What are the most critical features being built as part of this Epic
* Expected Outcome – Justification why this Feature must be built, what is expected value and justification for priority.

User feedback is that they find it difficult to track where a request is as they need to go into each request individually and see the comments. As a result some our still relying on their team inboxes which are the most common tool they use to prioritize there work.

The event queue will build off the functionality of the request queue.
----
**Sizing**

* T-shirt size: 

- [x] S
 - [ ] M
 - [ ] L
-  [ ] XL

(S=1-2 Sprints, M=2-3 Sprints, L=4-5 Sprints, XL=not sure, probably more than 5 Sprints). 

* *Risks and Assumptions**

1. [ ] What are assumptions?
2. [ ] What are the risks?
3. [ ] Have we done an RFC on a technical approach?
4. [ ] Are the dependencies (technical, business, regulatory/policy) known?
5. [ ] Has work on this Epic been prioritized with key stakeholders?

**Comment by KyEggleston** [comment]
Closing this epic, as it was released in 8.0
