### ISSUE TITLE
Doc reviewer known issues for 9.0 release

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#4651]
Title of ticket: 

#### Description
This ticket list down the known issues. 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Multiselect: Once done a multiselect operation other than edit, you have to click on top multiselect button to reenable multiselect to use the edit functionality
- [ ] Select an annotation of a page > 1000 and try to scroll the middle pane. The arrow pointer keep on moving with the scroll #4616
- [x] Issue with drawing the redaction box at the right position due to zoom issue #4570
- [x] Issue with page shows blank for documents > 1500+ pages #4586 - blank pages are showing for some files. This can be an issue with that particular file. We will be informing Apryse on this. Only workaround for now is to add a page to the issue file and replace the document with it.
- [ ] Undo option in doc reviewer - for redactions you need to click 2 times to undo it as it contains redaction box and free text for sections. 
- [ ] Undo click calls unnecessary apis
- [ ] Eraser button click calls unnecessary apis - tech. debt 
- [ ] The limit for bulk actions are set to 250.
- [ ] Docreviewer manual refresh is required if there is any change in records tab
- [ ] There is an issue with inflight request: converted pptx file's pagecount is updated as 1 in the BE even though it has more number of pages. To fix this, user has to delete the pptx file and reupload it again or upload the converted file.
- [ ] If a pdf have existing comments, then it will list in the notes panel.  The user has to remove any personal/sensitive information manually and reupload the pdf again - #4708
- [ ] last annotation is non selectable in notes panel multiselect if 100+ comments are there
- [ ] Attachment replacement issue #4704, #4705 - Possible action, Don't apply any flag to MSG attachment, if there is plan to replace for time being, Else we need to download entire MSG file and replace it with the same file , this will wipe all annotations, then we need to start from first on the first
